[package]
name = "kalshi-rust-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
